[keycloak]
address = "http://localhost:8080"
username = "tuadmin"
password = "tupwd"
realm = "master"

[logger]
filename = "roles-test.log"
level = "TRACE"
timestampFormat = "2006-01-02 15:04:05"
#rotation = false

[stock]
clientsAndRealmFolder = "../test/sample/test_config.d"
clientForRoles = "signauxfaibles"
usersAndRolesFilename = "../test/sample/userBase.xlsx"

#[wekan]
#username="wekan.ti"
#password="pwd"
