name: linter

on:
  push:

jobs:
  linter:
    name: lint code
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
