name: Publish  binary

  # @see https://github.com/marketplace/actions/go-release-binaries

#on:
#  release:
#    types: [created]

on:
  push:
    branches:
      - 'master'
      - 'feat*'
      - 'feat/*'
    tags:
      - 'v*'
  workflow_dispatch: # pour être lancé à la main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build binary
#        shell: bash
#        run: |
#          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
      #          cp ./datapi ./build-container
      #          cp -r ./migrations ./build-container
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          #          context: ./build-container
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}