name: Publish keycloakUpdater binary

# @see https://github.com/marketplace/actions/go-release-binaries

#on:
#  release:
#    types: [created]

push:
  tags:
    - 'v*'

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Publish binary
      uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        binary_name: keycloakUpdater
