name: CI - test

on:
  push:
    branches:

env:
  GOFLAGS: -mod=readonly

jobs:
  build_keycloakUpdater:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build package
        run: go build -v .

      - name: Unit Tests
        run: go test ./...

      - name: Liste les volumes inutilisés
        run: docker volume ls -qf dangling=true

      - name: Integration Tests
        run: go test -tags=integration
