name: CI

on:
  push:
    branches:

env:
  GOFLAGS: -mod=readonly

jobs:
  build_keycloakUpdater:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Build package
        run: go build -v .

      - name: Unit Tests
        run: go test ./...

      - name: Integration Tests
        run: go test -tags=integration
